---
- block:
    - name: Download golang
      ansible.builtin.shell: |
        curl -sSL -o /tmp/golang.tar.gz http://golang.org/dl/go{{ go_version }}.linux-{{ arch }}.tar.gz

    - name: Extract golang
      ansible.builtin.unarchive:
        src: "/tmp/golang.tar.gz"
        dest: "/usr/local"
        remote_src: yes

    - name: Change ownership of /usr/local/go
      ansible.builtin.file:
        path: "/usr/local/go"
        owner: "{{ circleci_user }}"
        group: "{{ circleci_user }}"
        state: directory
        recurse: yes

    - name: Change ownership of /usr/local/go directory
      ansible.builtin.file:
        path: "/usr/local/go"
        owner: "{{ circleci_user }}"
        group: "{{ circleci_user }}"
        state: directory
        recurse: yes

    - name: Make /.go_workspace directory
      ansible.builtin.file:
        path: "{{ circleci_home }}/.go_workspace"
        owner: "{{ circleci_user }}"
        group: "{{ circleci_user }}"
        state: directory
        mode: 0775
        recurse: yes

    - name: Configure golang
      ansible.builtin.blockinfile:
        path: "{{ circleci_home }}/.circlerc"
        marker_begin: "GOLANG START"
        marker_end: "GOLANG END"
        create: yes
        block: |
          export PATH=~/.go_workspace/bin:/usr/local/go/bin:$PATH
          export GOPATH=~/.go_workspace:/usr/local/go_workspace

    - name: Remove golang tar file
      ansible.builtin.file:
        path: "/tmp/golang.tar.gz"
        state: absent

  become: true
