---
- block:
  - name: Add mozilla ppa
    ansible.builtin.apt_repository:
      repo: "ppa:mozillateam/ppa"
      state: present

  # Because 22.04 now uses snap, these removals and resetting of repositories is needed to download firefox
  - name: Disable snap
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: stopped
      masked: true
    with_items: "{{ snaps }}"

  - name: Remove firefox via shell
    ansible.builtin.shell:
      apt remove firefox

  - name: Remove firefox with apt module
    ansible.builtin.apt:
      pkg: "firefox"
      state: absent
      clean: true
      purge: true
      autoremove: true

  - name: Remove snapd packages
    ansible.builtin.package:
      name: "{{ snapd_prefs }}"
      state: absent
      purge: true

  - name: Fully remove and purge snapd
    ansible.builtin.apt:
      name: "{{ snapd_prefs }}"
      autoremove: true
      autoclean: true
      purge: true
      state: absent

  - name: Blacklist snapd
    ansible.builtin.template:
      src: ../files/snapd.pref.j2
      path: etc/apt/preferences.d/snapd.pref
      mode: 0644

  - name: Blacklist snap firefox
    ansible.builtin.blockinfile:
      path: "/etc/apt/preferences"
      create: yes
      block: |
        Package: firefox
        Pin: version 1:1snap1-0ubuntu2
        Pin-Priority: 99

  - name: Clean up snap directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    with_items: "{{ snap_dirs }}"

  - name: Prioritze apt/debian download of firefox
    ansible.builtin.blockinfile:
      path: "/etc/apt/preferences.d/mozilla-firefox"
      marker_begin: "FIREFOX START"
      marker_end: "FIREFOX END"
      create: yes
      block: |
        Package: *
        Pin: release o=LP-PPA-mozillateam
        Pin-Priority: 1001

  - name: Install firefox
    ansible.builtin.apt:
      pkg: "firefox"
      state: present
      update_cache: yes
      allow_downgrade: true

  become: true
