---
- name: Install windows updates
  include_tasks: 'roles/windows/windows_updates/tasks/main.yml'

- name: Disable windows services
  include_tasks: 'roles/windows/disable_services/tasks/main.yml'

- name: install Build Agent Prerequisites
  include_tasks: 'roles/windows/buildagent_prereq/tasks/main.yml'
  
# https://docs.ansible.com/ansible/latest/collections/chocolatey/chocolatey/win_chocolatey_feature_module.html#ansible-collections-chocolatey-chocolatey-win-chocolatey-feature-module
- name: Enable Chocolatey Global Confirmation
  win_chocolatey_feature:
    name: allowGlobalConfirmation
    state: enabled

- name: load Chocolatey Profile
  ansible.windows.win_powershell:
    script: |
      @'
      # Chocolatey profile
      $ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
      if (Test-Path($ChocolateyProfile)) {
          Import-Module $ChocolateyProfile
      }
      refreshenv >$null 2>&1
      '@ | Out-File -Encoding ascii "${PSHOME}\Microsoft.PowerShell_profile.ps1"
