---
- name: Configure linux node
  hosts: all
  roles:
    - common
    - node
    - java
    - python3
    - ruby
    - firefox
    - chrome
    - docker
    - sysadmin_tools
    - devtools
    - ant
    - socat
    - nsenter
    - jq
    - yq
    - awscli
    - gcloud
    - clojure
    - golang
    - scala
    - dpkg_configure
  post_tasks:
    - name: Insert $BASH_ENV sourcing
      become: true
      ansible.builtin.shell:
        echo 'if ! echo $- | grep -q "i" && [ -n "$BASH_ENV" ] && [ -f "$BASH_ENV" ]; then . "$BASH_ENV"; fi' >> "{{ circleci_home }}/.bashrc"
  vars_files:
    - group_vars/linux_configure_vars.yml
