---
- name: Configure Remote Docker
  hosts: all
  roles:
    - common
    - docker
    - dpkg_configure
    - syft
  vars_files:
    - group_vars/linux_configure_vars.yml

  post_tasks:
    - name: Check if line is in file
      become_method: sudo
      become: true
      ansible.builtin.lineinfile:
        path: "{{ circleci_home }}/.bashrc"
        line: if ! echo $- | grep -q "i" && [ -n "$BASH_ENV" ] && [ -f "$BASH_ENV" ]; then . "$BASH_ENV"; fi
