---
- name: Configure windows node
  hosts: default
  connection: local
  roles:
    - windows/common
    - windows/install_cloudtools
    - windows/devtools
    - windows/microsoft_tools
  vars_files:
    - group_vars/windows_configure_vars.yml
    # - manifest/windows-software.json
