---
- name: Configure windows node
  hosts: default
  connection: local
  roles:
    - role: windows/create_users
      tags:
        - 'create_users'
    - role: windows/common
      tags:
        - 'common'
        - 'build'
    - role: windows/install_cloudtools
      tags:
        - 'cloudtools'
        - 'build'
    - role: windows/devtools
      tags:
        - 'devtools'
        - 'build'
    - role: windows/microsoft_tools
      tags:
        - 'ms_tools'
        - 'build'
  vars_files:
    - group_vars/windows_configure_vars.yml
