---
circleci_user: circleci
circleci_home: /home/circleci
python_versions:
  - 2.7.18
  - 3.11.2
python2_version: 2.7.18
python3_version: 3.11.2
pyenv_version: "v2.3.16"
pyenv_dir: "/opt/circleci/.pyenv"

pip:
  - virtualenv
  - nose
  - pep8
