---
- name: Install NVIDIA Display Driver
  win_chocolatey:
    name: nvidia-display-driver
    state: '{{ package_state }}'
    force: true

- name: Install CUDA Toolkit
  win_chocolatey:
    name: cuda
    state: '{{ package_state }}'
    version: '{{ cuda_version }}'
    force: true

- name: Verify NVIDIA Installation
  ansible.windows.win_command:
    cmd: nvidia-smi
  register: nvidia_check
