---
# !file: playbooks/linux/linux_configure.yml

- name: Configure linux node
  hosts: all
  connection: local
  roles:
    - system_prep
    - base
    - cci_specific
    - sysadmin_tools
    - devtools
    - ant
    - socat
    - nsenter
    - jq
    - yq
    - python3
    - java
    - firefox
    - chrome
    - awscli
    - gcloud
    - node
    - clojure
    - ruby
    - golang
    - scala
    - docker
    - dpkg_configure
  vars_files:
    - linux_configure_vars.yml
