version: 2.1

workflows:
  main:
    jobs:
      - ansible-check

jobs:
  ansible-check:
    docker:
      - image: cimg/deploy:2022.09.1
    
    steps:
      - checkout
      - run: ansible-playbook -i ~/project/playbooks/linux/hosts ~/project/playbooks/linux/linux_configure.yml
      - run: ansible-playbook -i ~/project/playbooks/linux/hosts ~/project/playbooks/linux/linux_configure.yml --check