version: 2.1

workflows:
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.12.1
    steps:
      - checkout
      - run: pip install -r ./project/tests/requirements.txt
      # TODO: Setup unit tests to run through here
