---
- name: Install sbt
  become: true
  ansible.builtin.apt:
    deb: https://scala.jfrog.io/artifactory/debian/sbt-{{ sbt_version }}.deb

- block:
    - name: Remove sbt .deb file
      ansible.builtin.file:
        path: "sbt-{{ sbt_version }}.deb"
        state: absent

    - name: Create and set permissions for sbt cache
      ansible.builtin.file:
        path: "{{ circleci_home }}/.cache"
        owner: "{{ circleci_user }}"
        group: "{{ circleci_user }}"
        state: directory

    - name: Create and set permissions for sbt
      ansible.builtin.file:
        path: "{{ circleci_home }}/.sbt"
        owner: "{{ circleci_user }}"
        group: "{{ circleci_user }}"
        mode: 0775
        state: directory

    - name: Display sbt version
      ansible.builtin.shell: sudo -u {{ circleci_user }} sbt -V

    - name: Remove sbt created folders
      ansible.builtin.file:
        path: "{{ circleci_home }}/{{ item }}"
        state: absent
      with_items: "{{ folders }}"

  become: true
