---
- name: Install Syft
  become: true
  ansible.builtin.shell:
    sudo curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin

- name: Deploy SBOM parser
  become: true
  ansible.builtin.copy:
    src: ../files/sbom
    dest: /usr/bin/sbom
    owner: "{{ circleci_user }}"
    group: "{{ circleci_user }}"
    mode: 6755

- name: Generate SBOM
  become: true
  ansible.builtin.shell: |
    "sbom generate {{ image_name }} {{ image_tag }}"
