---
- name: Install Syft
  become: true
  ansible.builtin.shell:
    sudo curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b /usr/local/bin

- name: Deploy SBOM parser
  become: true
  ansible.builtin.copy:
    src: ../files/sbom
    dest: /usr/bin/sbom
    owner: "{{ circleci_user }}"
    group: "{{ circleci_user }}"
    mode: a+x

- name: Generate SBOM
  become: true
  ansible.builtin.shell: |
    export PARAM_IMAGE_GROUP_NAME
    export PARAM_IMAGE_TAG
    sbom generate
