---
- block:
    - name: Create /opt/circleci/.pyenv directory
      ansible.builtin.file:
        path: "{{ pyenv_dir }}"
        owner: "{{ circleci_user }}"
        group: "{{ circleci_user }}"
        mode: 0775
        state: directory

    - name: Install pyenv dependencies
      ansible.builtin.apt:
        pkg:
          - libbz2-dev
          - libreadline-dev
          - libssl-dev
          - libsqlite3-dev
          - llvm
          - make
          - wget
          # may not need these
          - curl
          - libncurses5-dev
          - liblzma-dev
          - zlib1g-dev
          - python3-pip
        force_apt_get: yes
        force: yes
        state: latest
        update_cache: yes

    - name: Clone and checkout pyenv version
      # Intentionally uses shell instead of git module
      ansible.builtin.shell:
        "git clone --branch {{ pyenv_version }} --single-branch https://github.com/pyenv/pyenv.git {{ pyenv_dir }}"

    - name: Configure pyenv
      ansible.builtin.blockinfile:
        path: "{{ circleci_home }}/.circlerc"
        marker_begin: "PYTHON START"
        marker_end: "PYTHON END"
        block: |
          export PYENV_ROOT="{{ pyenv_dir }}"
          export PATH=$PYENV_ROOT/bin:$PATH
          export PATH=$PYENV_ROOT/shims:$PATH
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"

    - name: Install Python
      become_user: "{{ circleci_user }}"
      pyenv:
        versions: "{{ python }}"

    - name: Set Pyenv global
      become_user: "{{ circleci_user }}"
      ansible.builtin.shell:
        "sudo su circleci {{ pyenv_dir }}/bin/pyenv global {{ python2_version }} {{ python3_version }}"

    - name: Set Python for subsequent tasks
      ansible.builtin.set_fact:
        ansible_python_interpreter: "{{ pyenv_dir }}/shims/python3"

    - name: Install Pip Packages
      become_user: "{{ circleci_user }}"
      ansible.builtin.pip:
        name: "{{ item }}"
      with_items: "{{ pip }}"

  become: true
