- name: Install Syft
  win_chocolatey:
    name: syft
    state: '{{ package_state }}'
    version: '{{ syft_version }}'
    force: true

- name: Create SBOM folder
  ansible.windows.win_file:
    path: "/sbom"
    state: present

- name: Deploy SBOM parser
  ansible.windows.win_copy:
    src: ../../../syft/files/sbom
    dest:
