# !file: roles/linux-executor/tasks/circleci_specific.yml

- block:
    - name: redirect output (.bash_profile)
      lineinfile:
        path: '{{ circleci_home }}/.bash_profile'
        line: 'source ~/.bashrc &>/dev/null'
        create: yes

    - name: redirect output (.bashrc)
      lineinfile:
        path: '{{ circleci_home }}/.bashrc'
        line: 'source ~/.circlerc &>/dev/null'
        create: yes

    - name: source BASH_ENV via .bashrc
      lineinfile:
        path: '{{ circleci_home }}/.bashrc'
        line: 'if ! echo $- | grep -q "i" && [ -n "$BASH_ENV" ] && [ -f "$BASH_ENV" ]; then . "$BASH_ENV"; fi'
        create: yes

    - name: Change ownership of .bash_profile
      file:
        path: '{{ circleci_home }}/.bash_profile'
        owner: '{{ circleci_user }}'
        group: '{{ circleci_user }}'

    - name: Change ownership of .bashrc
      file:
        path: '{{ circleci_home }}/.bashrc'
        owner: '{{ circleci_user }}'
        group: '{{ circleci_user }}'

    - name: Add universe repository
      shell: add-apt-repository universe

    - name: Create and configure .circlecirc
      blockinfile:
        path: '{{ circleci_home }}/.circlecirc'
        owner: '{{ circleci_user }}'
        create: yes
        block: |
          export GIT_ASKPASS=echo
          export SSH_ASKPASS=false
          export PATH=~/bin:$PATH
          export CIRCLECI_PKG_DIR="/opt/circleci"

    - name: Create /bin directory
      file:
        path: '{{ circleci_home }}/bin'
        owner: '{{ circleci_user }}'
        state: directory

    - name: Create and configure ssh_config
      blockinfile:
        path: '/etc/ssh/ssh_config'
        create: yes
        block: |
          Host *
          StrictHostKeyChecking no
          HashKnownHosts no
          SendEnv LANG LC_*
          
    - name: Some optimizations for the sshd daemon
      lineinfile:
        path: '/etc/ssh/sshd_config'
        search_string: 'PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        create: yes
        backup: yes

    - name: Some more optimizations for the sshd daemon
      blockinfile:
        path: '/etc/ssh/sshd_config'
        backup: yes
        block: |
          UseDns no
          MaxStartups 1000
          MaxSessions 1000
          PermitTunnel yes
          AddressFamily inet

    - name: Install xvfb
      apt:
        name: xvfb
        state: present

    - name: Install xfwm4
      apt:
        name: xfwm4
        state: present

    - name: Configure xvfb service
      blockinfile:
        path: '/etc/systemd/system/xvfb.service'
        backup: yes
        create: yes
        block: |
          [Unit]
          Description=XVFB Service
          After=network.target

          [Service]
          ExecStart=/usr/bin/Xvfb :99 -screen 0 1280x1024x24
          Type=simple

          [Install]
          WantedBy=multi-user.target

    - name: Change permissions on xvfb.service
      file:
        path: '/etc/systemd/system/xvfb.service'
        mode: '0644'

    - name: set display settings in .circlecirc
      lineinfile:
        path: '{{ circleci_home }}/.circlecirc'
        line: 'export DISPLAY=:99'
        create: yes

    - name: Enable xvfb.service
      systemd:
        name: 'xvfb.service'
        enabled: yes

    - name: Start xvfb.service
      systemd:
        name: 'xvfb.service'
        state: started

    - name: Add an apt key by id from a keyserver
      shell: |
        apt-key adv --keyserver keyserver.ubuntu.com --recv-key 514A2AD631A57A16DD0047EC749D6EEC0353B12C
        apt-key adv --keyserver keyserver.ubuntu.com --recv-key 58118E89F3A912897C070ADBF76221572C52609D

    - name: A tweak to make selenium tests stable
      lineinfile:
        path: '{{ circleci_home }}/.circlecirc'
        line: 'export DBUS_SESSION_BUS_ADDRESS=/dev/null'
        create: yes

    - name: Allow iptable rules to be saved
      shell: |
        echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
        echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
        apt-get -y install iptables-persistent

  become: true
  become_method: sudo
