# !file: roles/linux-executor/tasks/circleci_specific.yml

- name: redirect output (.bash_profile)
  lineinfile:
    path: "{{ circleci_home }}/.bash_profile"
    line: 'source ~/.bashrc &>/dev/null'
    create: yes

- name: redirect output (.bashrc)
  lineinfile:
    path: "{{ circleci_home }}/.bashrc"
    line: 'source ~/.circlerc &>/dev/null'
    create: yes

- name: source BASH_ENV via .bashrc
  lineinfile:
    path: "{{ circleci_home }}/.bashrc"
    line: 'if ! echo $- | grep -q "i" && [ -n "$BASH_ENV" ] && [ -f "$BASH_ENV" ]; then . "$BASH_ENV"; fi'
    create: yes

- name: Change ownership of .bash_profile
  file:
    path: "{{ circleci_home }}/.bash_profile" 
    owner: "{{ circleci_user }}"
    group: "{{ circleci_user }}"

- name: Change ownership of .bashrc
  file:
    path: "{{ circleci_home }}/.bashrc" 
    owner: "{{ circleci_user }}"
    group: "{{ circleci_user }}"

- name: Add universe repository
  become: true
  become_method: sudo
  shell: add-apt-repository universe

- name: Create and configure .circlecirc
  blockinfile:
    path: "{{ circleci_home }}/.circlecirc"
    owner: "{{ circleci_user }}"
    create: yes
    block: |
      export GIT_ASKPASS=echo
      export SSH_ASKPASS=false
      export PATH=~/bin:$PATH
      export CIRCLECI_PKG_DIR="/opt/circleci"

- name: Create /bin directory
  file:
    path: "{{ circleci_home }}/bin"
    owner: "{{ circleci_user }}"
    state: directory

- name: Create and configure ssh_config
  blockinfile:
    path: '/etc/ssh/ssh_config'
    create: yes
    block: |
      Host *
      StrictHostKeyChecking no
      HashKnownHosts no
      SendEnv LANG LC_*

- name: Some optimizations for the sshd daemon
  lineinfile:
    path: '/etc/ssh/sshd_config'
    search_string: 'PasswordAuthentication yes'
    line: 'PasswordAuthentication no'
    backup: yes

- name: Some more optimizations for the sshd daemon
  blockinfile:
    path: '/etc/ssh/sshd_config'
    backup: yes
    block: |
      UseDns no
      MaxStartups 1000
      MaxSessions 1000
      PermitTunnel yes
      AddressFamily inet

  
   



