# !file: roles/linux-executor/tasks/install_java.yml
- block:
    - name: Add openjdk from PPA
      shell: add-apt-repository ppa:openjdk-r/ppa

    - name: Install java
      apt:
        name: openjdk-{{ item }}-jdk
        state: present
        update_cache: yes
      with_items: '{{ java_versions }}'

    - name: set java links
      community.general.alternatives:
        name: java
        path: '/usr/lib/jvm/java-{{ item }}-openjdk-amd64/bin/java'
      with_items: '{{ java_versions }}'

    - name: set javac links
      community.general.alternatives:
        name: javac
        path: '/usr/lib/jvm/java-{{ item }}-openjdk-amd64/bin/javac'
      with_items: '{{ java_versions }}'

    - name: set javadoc links
      community.general.alternatives:
        name: javadoc
        path: '/usr/lib/jvm/java-{{ item }}-openjdk-amd64/bin/javadoc'
      with_items: '{{ java_versions }}'

  become: true
  become_method: sudo
