# !file: roles/linux-executor/tasks/install_maven.yml
- block:
  - name: Download maven
    get_url:
      url: 'http://apache.osuosl.org/maven/maven-3/{{maven_version}}/binaries/apache-maven-{{maven_version}}-bin.tar.gz'
      dest: '/tmp/maven.tar.gz'

  - name: Extract maven
    unarchive:
      src: '/tmp/maven.tar.gz'
      dest: '/usr/local'

  - name: Create a maven symbolic link
    file:
      src: '/usr/local/apache-maven-{{maven_version}}'
      dest: '/usr/local/apache-maven'
      state: link

  - name: Remove maven tar file
    file:
      path: '/tmp/maven.tar.gz'
      state: absent

  become: true
  become_method: sudo

- name: Create maven .m2 directory
  file:
    path: "{{ circleci_home }}/.m2"
    owner: "{{ circleci_user }}"
    state: directory

- name: Configure maven in .circlecirc
  blockinfile:
    path: "{{ circleci_home }}/.circlecirc"
    owner: "{{ circleci_user }}"
    marker_begin: "MAVEN BEGIN"
    marker_end: "MAVEN END"
    create: yes
    block: |
      export M2_HOME=/usr/local/apache-maven
      export MAVEN_OPTS=-Xmx2048m
      export PATH=$M2_HOME/bin:$PATH
      