# !file: roles/linux-executor/tasks/install_awscli.yml

- block:
    - name: download awscli
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"

    - name: extract awscli
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"

    - name: install awscli
      shell: |
        ./aws/install -i /usr/local/aws-cli -b /usr/local/bin

    - name: remove awscli
      file:
        path: "/tmp/awscliv2.zip"
        state: absent

  become: true
  become_method: sudo
