# !file: roles/linux-executor/tasks/install_nodejs.yml
- block:
    - name: Install nodejs dependencies
      shell: apt-get install build-essential libssl-dev make g++ curl libssl-dev

    - name: Download nvm script
      get_url:
        url: 'https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh'
        dest: '/tmp/nvm.sh'

    - name: Create nvm dir
      file:
        path: '{{ nvm_dir }}'
        owner: "{{ circleci_user }}"
        group: "{{ circleci_user }}"
        state: directory

    - name: Run nvm install script
      script: '/tmp/nvm.sh'
      environment:
        NVM_DIR: '{{ nvm_dir }}'

    - name: configure nvm
      blockinfile:
        path: '{{ circleci_home }}/.circlerc'
        owner: '{{ circleci_user }}'
        group: '{{ circleci_user }}'
        marker_begin: "NODE START"
        marker_end: "NODE END"
        create: yes
        block: |
          export NVM_DIR={{ nvm_dir }}
          source {{ nvm_dir }}/nvm.sh
          export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

    - name: Install nodejs and common items
      shell:
        source {{ circleci_home }}/.circlerc
        nvm install {{ item }}
        rm -rf {{ circleci_home }}/nvm/src
        hash -r
        nvm use {{ item }}
        npm install -g npm
        npm install -g coffee-script
        npm install -g grunt
        npm install -g bower
        npm install -g grunt-cli
        npm install -g nodeunit
        npm install -g mocha
        npm install -g yarn@{{ yarn_version }}
        hash -r
        nvm alias default 16.16.0
      args:
        executable: /bin/bash
      with_items: '{{ nodejs_versions }}'

  become: true
  become_method: sudo
