# !file: roles/linux-executor/tasks/install_nsenter.yml

- block:
    - name: Install tools to compile nsenter
      apt:
        pkg:
          - build-essential
          - libncurses5-dev
          - libslang2-dev
          - gettext
          - zlib1g-dev
          - libselinux1-dev
          - debhelper
          - lsb-release
          - pkg-config
          - po-debconf
          - autoconf
          - automake
          - autopoint
          - libtool
          - util-linux
        state: present
        update_cache: yes

  become: true
  become_method: sudo
