# !file: roles/linux-executor/tasks/install_nodejs.yml
- block:
    - name: Install nodejs dependencies
      become: true
      become_method: sudo
      shell: apt-get install build-essential libssl-dev make g++ curl libssl-dev

    - name: Download nvm script
      get_url:
        url: 'https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh'
        dest: '/tmp/nvm.sh'

    - name: Create nvm dir
      file:
        path: '{{ nvm_dir }}'
        state: directory

    - name: Run nvm install script
      script: '/tmp/nvm.sh'
      environment:
        NVM_DIR: '{{ nvm_dir }}'

    - name: configure nvm
      blockinfile:
        path: '{{ circleci_home }}/.circlerc'
        owner: '{{ circleci_user }}'
        group: '{{ circleci_user }}'
        create: yes
        block: |
          export NVM_DIR={{ nvm_dir }}
          source {{ nvm_dir }}/nvm.sh

    - name: Install nodejs and common items
      shell: |
        export NVM_DIR="{{ nvm_dir }}"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
        source {{ circleci_home }}/.circlerc
        nvm install {{ item }}
        rm -rf {{ circleci_home }}/nvm/src
        hash -r
        nvm use {{ item }}
        npm install -g npm
        npm install -g coffee-script
        npm install -g grunt
        npm install -g bower
        npm install -g grunt-cli
        npm install -g nodeunit
        npm install -g mocha
        hash -r
        nvm alias default 16.16.0
      with_items: '{{ nodejs_versions }}'

  become: true
  become_method: sudo
