# !file: roles/linux-executor/tasks/install_yq.yml

- block:
    - name: download yq
      get_url:
        url: 'https://github.com/mikefarah/yq/releases/download/v4.24.5/yq_linux_amd64.tar.gz'
        dest: '/tmp/yq.tar.gz'

    - name: Create /tmp/yq directory
      file:
        path: '/tmp/yq'
        state: directory

    - name: extract yq
      unarchive:
        src: '/tmp/yq.tar.gz'
        dest: '/tmp/yq'

    - name: list files
      shell: |
        ls -al /tmp/yq

    - name: copy yq files
      copy:
        src: '/tmp/yq/yq_linux_amd64'
        dest: '/usr/local/bin/yq'

  become: true
  become_method: sudo
