# !file: roles/linux-executor/tasks/install_python.yml

- block:
    - name: Create /opt/circleci/.pyenv directory
      file:
        path: '{{ pyenv_dir }}'
        owner: '{{ circleci_user }}'
        group: '{{ circleci_user }}'
        state: directory

    - name: Install pyenv dependencies
      shell: |
        apt-get install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
          libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev liblzma-dev

    - name: Install python3-pip
      apt:
        name: 'python3-pip'
        state: present
        update_cache: yes

  become: true
  become_method: sudo

- block:
    - name: Clone pyenv repo
      git:
        repo: 'https://github.com/yyuu/pyenv.git'
        dest: '{{ pyenv_dir }}'
        single_branch: yes
        version: master

    - name: Checkout pyenv version
      git:
        repo: 'https://github.com/yyuu/pyenv.git'
        dest: '{{ pyenv_dir }}'
        version: "{{ pyenv_version }}"

    - name: Configure pyenv
      blockinfile:
        path: '{{ circleci_home }}/.circlerc'
        owner: '{{ circleci_user }}'
        group: '{{ circleci_user }}'
        marker_begin: "PYTHON START"
        marker_end: "PYTHON END"
        create: yes
        block: |
          export PYENV_ROOT="{{ pyenv_dir }}"
          export PATH=$PYENV_ROOT/bin:$PATH
          export PATH=$PYENV_ROOT/shims:$PATH
          eval "$(pyenv init --path)"
          eval "$(pyenv init -)"

    - name: Install python versions
      shell: |
        source {{ circleci_home }}/.circlerc
        {{ pyenv_dir }}/bin/pyenv install {{ item }}
        {{ pyenv_dir }}/bin/pyenv global {{ item }}
        {{ pyenv_dir }}/bin/pyenv rehash
        pip install -U virtualenv
        pip install -U nose
        pip install -U pep8
      with_items: '{{ python_versions }}'

  become: true
  become_user: '{{ circleci_user }}'
  become_method: sudo

- name: set pyenv global versions
  become: true
  become_method: sudo
  shell: sudo -H -i -u {{ circleci_user }} {{ pyenv_dir }}/bin/pyenv global {{ python2_version }} {{ python3_version }}
