# !file: roles/linux-executor/tasks/install_firefox.yml
- block:
  - name: Add mozilla ppa
    shell: add-apt-repository ppa:mozillateam/ppa

  - name: Remove firefox via shell 
    shell:
      apt remove firefox

  - name: Remove firefox with apt module
    apt:
      pkg: firefox
      state: absent
      purge: true

  - name: Blacklist snap firefox
    blockinfile:
      path: '/etc/apt/preferences'
      create: yes
      block: |
        Package: firefox
        Pin: version 1:1snap1-0ubuntu2
        Pin-Priority: 99

  - name: Prioritze apt/debian download of firefox
    blockinfile:
      path: '/etc/apt/preferences.d/mozilla-firefox'
      marker_begin: "firefox"
      marker_end: "firefox"
      create: yes
      block: |
        Package: *
        Pin: release o=LP-PPA-mozillateam
        Pin-Priority: 1001

  - name: Install firefox
    apt:
      name: 'firefox'
      state: present
      update_cache: yes

  become: true
  become_method: sudo
