# !file: roles/linux-executor/tasks/install_yarn.yml

- name: install yarn
  become: true
  become_method: sudo
  shell:
    cmd:
      cat <<EOF
      source {{ circleci_home }}/.circlerc
      curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version "{{ yarn_version }}"
      EOF | sudo -H -i -u {{ circleci_user }} bash
  args:
    executable: /bin/bash
