# !file: roles/windows-executor/tasks/create_circleci_windows_users.yml

- name: Create circleci user passwords
  set_fact:
    cci_user_pwd: "{{ lookup('password', '/dev/null length=42 chars=ascii_letters,digits,punctuation') }}"
    cci_admin_pwd: "{{ lookup('password', '/dev/null length=42 chars=ascii_letters,digits,punctuation') }}"

- name: Create circeci user 
  win_user:
    name: circleci
    password: "{{ cci_user_pwd }}"
    state: present
    groups:
      - Administrators

- name: Create circeci-admin user 
  win_user:
    name: circleci-admin
    password: "{{ cci_admin_pwd }}"
    state: present
    groups:
      - Administrators

