# !file: roles/windows-executor/tasks/create_circleci_windows_users.yml

- name: Create circleci users
  set_fact:
    cipassword: "{{ lookup('password', '/dev/null length=42 chars=ascii_letters,digits,punctuation') }}"
