# !file: roles/windows-executor/tasks/create_circleci_windows_users.yml

- name: Create circleci users
  set_fact:
    cci_user_pwd: "{{ lookup('password', '/dev/null length=42 chars=ascii_letters,digits,punctuation') }}"
  win_user:
    name: circleci
    password: "{{ cci_user_pwd }}"
    state: present
    groups:
      - Administrators

