# !file: roles/windows-executor/tasks/disable_windows_services.yml

- name: Disable IE ESC
  script: disable_default_winservices.ps1 Disable-IEESC

- name: Disable IE Welcome screen
  script: disable_default_winservices.ps1 Disable-InternetExplorerWelcomeScreen

- name: Disable UAC (User Access Control)
  script: disable_default_winservices.ps1 Disable-UserAccessControl

- name: Enable Long Paths 
  script: disable_default_winservices.ps1 Disable-LongPaths

- name: Enable .NET 3.5
  script: disable_default_winservices.ps1 Enable-DotNet35

- name: Disable network wizard
  script: disable_default_winservices.ps1 Disable-NetworkWizard

- name: Disable password complexity
  script: disable_default_winservices.ps1 Disable-PasswordComplexity

- name: Disable TDR
  win_regedit:
    path: HKLM:\System\CurrentControlSet\Control\GraphicsDrivers
    name: TdrLevel
    data: 0
    type: dword
    state: present

- name: Enable Hyper-V
  ansible.windows.win_powershell:
    script: |
      Install-WindowsFeature -Name Hyper-V -IncludeManagementTools -Restart

- name: Reboot the machine after enabling Hyper-V
  ansible.windows.win_reboot:

- name: Display windows features to check if Hyper-V is enabled
  ansible.windows.win_powershell:
    script: |
      Get-WindowsFeature

  