# !file: roles/windows-executor/tasks/install_cloud_tools.yml

- name: Install awscli
  win_chocolatey:
    name: awscli
    state: '{{ package_state }}'
    version: '{{ awscli_version }}'

- name: Install azure-cli
  win_chocolatey:
    name: azure-cli
    state: '{{ package_state }}'
    version: '{{ azurecli_version }}'

- name: Install web platform installer
  win_chocolatey:
    name: webpi
    state: '{{ package_state }}'
    version: '{{ webpi_version }}'

- name: Install service fabric sdk
  script: install_servicefabric_sdk.ps1