# !file: roles/windows-executor/tasks/install_windows_updates.yml

- name: Install PowershellGet
  ansible.windows.win_powershell:
    script: |
      Install-PackageProvider -Name NuGet -Force
      Install-Module PowerShellGet -Force -AllowClobber -Confirm:$false

- name: Register nuget repository
  community.windows.win_psrepository:
    name: Nuget
    source_location: https://nuget.org/api/v2/
    installation_policy: trusted
    state: present

- name: Install all security, critical, and rollup updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: yes
   