# !file: roles/windows-executor/tasks/install_windows_updates.yml

- name: Install all security, critical, and rollup updates
  set_fact: computer_name="{{ lookup('env','COMPUTERNAME') }}"
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
    reboot: yes
   