- name: Install awscli
  win_chocolatey:
    name: awscli
    state: '{{ package_state }}'
    version: '{{ awscli_version }}'

- name: Install azure-cli
  win_chocolatey:
    name: azure-cli
    state: '{{ package_state }}'
    version: '{{ azurecli_version }}'

- name: Install web platform installer
  win_chocolatey:
    name: webpi
    state: '{{ package_state }}'
    version: '{{ webpi_version }}'

#- name: Install powershellget
#  script: install_powershellget.ps1

- name: Register nuget repository
  community.windows.win_psrepository:
    name: Nuget
    source_location: https://nuget.org/api/v2/
    installation_policy: trusted
    state: present

- name: Install service fabric sdk
  script: install_servicefabric_sdk.ps1