---
- block:
    - name: Install packages to allow apt to use a repository over https
      ansible.builtin.apt:
        pkg:
          - ca-certificates
          - curl
          - gnupg-agent
          - lsb-release
        state: present
        update_cache: yes

    # - name: Install docker's official gpg keyring
    #   ansible.builtin.apt_key:
    #     url: https://download.docker.com/linux/ubuntu/gpg
    #     keyring: /etc/apt/keyrings/docker.gpg
    #     state: present
    
    - name: Install docker's official gpg keyring new
      ansible.builtin.shell: |
        sudo apt-get update
        sudo apt-get install ca-certificates curl gnupg
        sudo install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        sudo chmod a+r /etc/apt/keyrings/docker.gpg
        

    - name: Set up docker repository
      ansible.builtin.shell: |
        echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        grep -ri docker /etc/apt

    - name: Install docker and docker compose (*put versions back here eventually)
      ansible.builtin.apt:
        name:
          - docker-ce={{ docker_version }}
          - docker-ce-cli={{ docker_version }}
          - containerd.io={{ containerd_version }}
          - docker-compose-plugin={{ docker_compose_version }}
        state: present
        allow_downgrade: yes
        force: yes
        update_cache: yes

    - name: Install docker compose switch
      ansible.builtin.shell: |
        curl -fL https://raw.githubusercontent.com/docker/compose-switch/master/install_on_linux.sh | sh
        chmod +x /usr/local/bin/compose-switch
        update-alternatives --install /usr/local/bin/docker-compose docker-compose /usr/local/bin/compose-switch 99

    - name: Add circleci to docker group
      ansible.builtin.shell:
        sudo usermod -aG docker {{ circleci_user }}

  become: true
