---
# !file: playbooks/windows/win_configure.yml

- name: Configure windows node
  hosts: default
  connection: local
  roles:
    - ../../../roles/windows-executor
  vars_files:
    - win_configure_vars.yml
