---
- name: Configure dpkg
  become: true
  ansible.builtin.shell: |
    dpkg --configure -a debconf
    systemctl mask apt-daily.service
    systemctl mask apt-daily-upgrade.service
    systemctl mask apt-daily.timer
    systemctl mask apt-daily-upgrade.timer
