---
- block:
    - name: Install rbenv
      become_method: sudo
      ansible.builtin.apt:
        pkg:
          - rbenv
          - libyaml-dev
        state: present
        update_cache: yes

    - name: Add .rbenv/bin to path
      ansible.builtin.blockinfile:
        path: "{{ circleci_home }}/.circlerc"
        create: yes
        marker_begin: "RUBY START"
        marker_end: "RUBY END"
        block: |
          export PATH="{{ circleci_home }}/.rbenv/bin:$PATH"
          eval "$(rbenv init -)"

    - name: Configure permissions for ruby
      ansible.builtin.file:
        path: "{{ ruby_dir }}"
        owner: "{{ circleci_user }}"
        group: "{{ circleci_user }}"
        recurse: true
        state: directory

    - name: Configure .gemrc
      ansible.builtin.blockinfile:
        path: "{{ gemrc_file }}"
        owner: "{{ circleci_user }}"
        group: "{{ circleci_user }}"
        mode: 0664
        create: yes
        block: |
          :sources:
          - https://rubygems.org
          gem:  --no-ri --no-rdoc

    - name: Install rubygems (ruby-dev)
      become_method: sudo
      ansible.builtin.apt:
        pkg:
        - ruby-dev
        state: present
        update_cache: yes

    - name: Install Ruby Build
      ansible.builtin.shell: |
        git clone https://github.com/rbenv/ruby-build.git "{{ ruby_dir }}"/plugins/ruby-build
        PREFIX=/usr/local sudo "{{ ruby_dir }}/plugins/ruby-build/install.sh"

    - name: Install ruby
      become_user: "{{ circleci_user }}"
      become_method: sudo
      rbenv:
        versions: "{{ ruby }}"
        default: "{{ defaults.ruby }}"

  become: true
